export enum QUESTION_DIFFICULTY {
  FACIL = 'FACIL',
  MEDIO = 'MEDIO',
  DIFICIL = 'DIFICIL',
}

export enum QUIZ_TYPE {
  SIMULADO = 'SIMULADO',
  QUESTIONARIO = 'QUESTIONARIO',
  ATIVIDADE = 'ATIVIDADE',
}

export enum QUESTION_TYPE {
  ALTERNATIVA = 'ALTERNATIVA',
  DISSERTATIVA = 'DISSERTATIVA',
  MULTIPLA_ESCOLHA = 'MULTIPLA_ESCOLHA',
  VERDADEIRO_FALSO = 'VERDADEIRO_FALSO',
  LIGAR_PONTOS = 'LIGAR_PONTOS',
  PREENCHER = 'PREENCHER',
  IMAGEM = 'IMAGEM',
}

export enum QUESTION_STATUS {
  PENDENTE_AVALIACAO = 'PENDENTE_AVALIACAO',
  RESPOSTA_CORRETA = 'RESPOSTA_CORRETA',
  RESPOSTA_INCORRETA = 'RESPOSTA_INCORRETA',
}

export enum ANSWER_STATUS {
  AVALIADO = 'AVALIADO',
  PENDENTE = 'PENDENTE',
}

export enum SUBTYPE_ENUM {
  PROVA = 'PROVA',
  ENEM_PROVA_1 = 'ENEM_PROVA_1',
  ENEM_PROVA_2 = 'ENEM_PROVA_2',
  VESTIBULAR = 'VESTIBULAR',
  SIMULADO = 'SIMULADO',
  SIMULADAO = 'SIMULADAO',
}

export const useQuizStore = jest.fn();
