name: Setup Dependencies

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key for node_modules"
        value: ${{ jobs.setup.outputs.cache-key }}

jobs:
  setup:
    name: Setup Node.js and Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Generate cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
            .pnp.*
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile