name: SonarCloud Analysis

on:
  workflow_call:
    inputs:
      cache-key:
        description: "Cache key for node_modules"
        required: true
        type: string

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que o histórico completo do Git está disponível para análise

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            .yarn/cache
            .pnp.*
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: true

      - name: Download Coverage Reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

      - name: Run SonarCloud Scanner
        run: npx sonarqube-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
