name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests with Coverage (80% minimum)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run Tests with Coverage
        run: yarn test

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
